blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/InfinitIQ-Tech/mcp-jira/blob/main/README.md
    about: Check the README for setup and usage instructions
  - name: 💬 Discussions
    url: https://github.com/InfinitIQ-Tech/mcp-jira/discussions
    about: Ask questions and discuss ideas with the community